runtime: python38
env: flex
entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static/
  static_dir: static

- url: /js
  static_dir: static/js

- url: /images
  static_dir: static/images
  
- url: /css
  static_dir: static/css

- url: .*
  script: main.app

runtime_config:
    python_version: 3